### ISSUE TITLE
IFlag conflict with SRS Studio

### ISSUE THREAD

**Issue by mundtster** [pwitab/iflag#2]
IFlag when running prevents SRS Studio software from recognizing tachometer and LED.  Please resolve conflict so IFlag can run concurrently with SRS Studio which controls my StImulator.  Thanks!

**Comment by Krolken** [comment]
Can you please describe the problem a bit more? 
What is SRS Studio? What simulator? Some quick googling got me to SimRacingStudio. So what in a smart meter communications protocol library is blocking your racing simulator?

Cheers.

**Comment by mundtster** [comment]
Sim racing Studio is SRS www.simracingstudio.com. I use this software for my P3 DOF Realty Racing Simulator, which integrates a tachometer vis Simracngstudio software.  When running the software while running IFlag it creates a conflict and prevents simracingstudio software from connecting to the tachometer with LED lighting synched to iracing.  Once I close IFlag software the problem is resolved, but I can’t run IFlag which I hope you can resolve.  I would like to run both but needs to be addressed in both software.

**Comment by Krolken** [comment]
OK. How did you install iflag and how are you using it? Any code examples you can share?

**Comment by Krolken** [comment]
Is this the iflag you are refering too: https://iracingiflag.com/iracingiflag?
That has nothing at all to do with this library, I am afraid. This library is used to read iflag protocol for reading values from industrial gas meters.

**Comment by Krolken** [comment]
closing due to irrelevance
